program Converter;

uses
  Forms,
  Main in 'Main.pas' {MainForm},
  TypeInterface in 'TypeInterface.pas',
  Prefixes in 'Prefixes.pas' {,
  Length in 'Length.pas',
  Massa in 'Massa.pas',
  Time in 'Time.pas',
  MomentInertia in 'MomentInertia.pas',
  MomentResistance in 'MomentResistance.pas',
  Square in 'Square.pas',
  Volume in 'Volume.pas',
  Force in 'Force.pas',
  Pressure in 'Pressure.pas',
  Speed in 'Speed.pas',
  Density in 'Density.pas',
  Temperature in 'Temperature.pas',
  Power in 'Power.pas',
  DataVolume in 'DataVolume.pas',
  Moment in 'Moment.pas',
  Accelerator in 'Accelerator.pas',
  DynamicMoment in 'DynamicMoment.pas',
  MolarVolume in 'MolarVolume.pas',
  MassFlow in 'MassFlow.pas',
  VolumeFlow in 'VolumeFlow.pas',
  EnergyWork in 'EnergyWork.pas',
  DynamicViscosity in 'DynamicViscosity.pas',
  KinematicViscosity in 'KinematicViscosity.pas',
  Amperage in 'Amperage.pas',
  Charge in 'Charge.pas',
  Voltage in 'Voltage.pas',
  Corner in 'Corner.pas',
  Capacity in 'Capacity.pas',
  Resistance in 'Resistance.pas',
  AngularAcceleration in 'AngularAcceleration.pas',
  AngularVelocity in 'AngularVelocity.pas',
  TransferRate in 'TransferRate.pas',
  Frequency in 'Frequency.pas'},
  Length in 'Length.pas',
  Massa in 'Massa.pas',
  Time in 'Time.pas',
  MomentInertia in 'MomentInertia.pas',
  MomentResistance in 'MomentResistance.pas',
  Square in 'Square.pas',
  Volume in 'Volume.pas',
  Force in 'Force.pas',
  Pressure in 'Pressure.pas',
  Speed in 'Speed.pas',
  Density in 'Density.pas',
  Temperature in 'Temperature.pas',
  Power in 'Power.pas',
  DataVolume in 'DataVolume.pas',
  Moment in 'Moment.pas',
  Accelerator in 'Accelerator.pas',
  DynamicMoment in 'DynamicMoment.pas',
  MolarVolume in 'MolarVolume.pas',
  MassFlow in 'MassFlow.pas',
  VolumeFlow in 'VolumeFlow.pas',
  EnergyWork in 'EnergyWork.pas',
  DynamicViscosity in 'DynamicViscosity.pas',
  KinematicViscosity in 'KinematicViscosity.pas',
  Amperage in 'Amperage.pas',
  Charge in 'Charge.pas',
  Voltage in 'Voltage.pas',
  Corner in 'Corner.pas',
  Capacity in 'Capacity.pas',
  Resistance in 'Resistance.pas',
  AngularAcceleration in 'AngularAcceleration.pas',
  AngularVelocity in 'AngularVelocity.pas',
  TransferRate in 'TransferRate.pas',
  Frequency in 'Frequency.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'Конвертер';
  Application.CreateForm(TMainForm, MainForm);
  Application.Run;
end.
